[package]
name = "rimg"
version = "0.1.0"
edition = "2021"
authors = ["CroxxN <saradgaihre19@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clap = {version = "4.0.18", features=["derive"]}
